### ISSUE TITLE
Could you please make a release in tar.gz format?

### ISSUE THREAD

**Issue by onkelbeh** [majuss/pypca#2]
Hi,

I would like to use your integration in my [Gentoo Overlay for Home Assistant](https://github.com/onkelbeh/HomeAssistantRepository).
Therefor I need a release file in tar.gz format.
Home Assistant currently requires: `pypca==0.0.5`
This one exists at Pypi, but only in wheel format, cannot use this.

A release on Github would also be OK, but a Pypi tar.gz release would be preferred, because this could use Gentoo's mirror system.

Thanks
 \B.

**Comment by majuss** [comment]
Done, let me know if it works!

**Comment by onkelbeh** [comment]
Thanks, partly.
Could not find it on Pypi,
so I took the one from `https://github.com/majuss/${PN}/archive/${PV}.tar.gz`
Filed it with https://github.com/onkelbeh/HomeAssistantRepository/commit/5f007db5429b67c3389d8887cdd91635a28ce064.
It compiles in Gentoo's build system without problems.

There's only the `0.0.6`, Home Assistant currently insists on `pypca==0.0.5`.
I don't know when it will be bumped, could you please file the `0.0.5`, too?
Or make the HA Guys bump it to `0.0.6`?

**Comment by majuss** [comment]
I bumped the version to `0.0.7` and created a tarball on pypi. To use it on hass please just change the version in the requirements file and inside the manifest of the elv integration. I will open a pr for a version bump as soon as my other prs are through.

**Comment by majuss** [comment]
Here you go, I managed to create a new branch of off my fork and created a PR for the bump: https://github.com/home-assistant/home-assistant/pull/28976

**Comment by onkelbeh** [comment]
That's cool, thanks :-)

**Comment by onkelbeh** [comment]
Hope you don't mind:
in the meantime I added [a fork with the current version](https://github.com/onkelbeh/HomeAssistantRepository/commit/12961f7f40c3faf8434d287bf81eb37eece13784).

**Comment by onkelbeh** [comment]
Back on Pypi again, thanks.
https://github.com/onkelbeh/HomeAssistantRepository/commit/6119209b5965d775a4d2faff07f7336c80922f1e
